"""Selects which node implementation the app runs, from config (or the KUMO_ENGINE override).

- "live"      → RedisConsumer (reads the engine process's `ui:stream` — the engine runs separately, so a
                UI restart never stops trading; see #20). No Nautilus node in this process.
- "synthetic" → NodeManager (offline BacktestEngine with demo bars + positions; tests/CI).

Both satisfy the `Node` protocol the WS/REST layer depends on.
"""

from __future__ import annotations

import os
from typing import Protocol

from api.models import (
    AccountDTO,
    BarDTO,
    ExternalActivityDTO,
    FillDTO,
    FundamentalsDTO,
    OrderDTO,
    PositionDTO,
    PriceDTO,
    QuoteDTO,
    TodayRangeDTO,
    TradeDTO,
    VwapDTO,
)


class Node(Protocol):
    """The read surface the FastAPI layer needs from whichever engine is running."""

    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    def positions(self) -> list[PositionDTO]: ...
    def trades(self) -> list[TradeDTO]: ...
    def trades_health(self) -> tuple[str | None, str | None]: ...
    def trades_realized(self) -> dict | None: ...
    def trades_periods(self) -> dict | None: ...
    def trades_periods_swept(self) -> dict | None: ...
    def trades_legs(self) -> dict | None: ...
    def trades_flows(self) -> dict | None: ...
    def external(self) -> list[ExternalActivityDTO]: ...
    def strategy_position(self, instrument_id: str, strategy_id: str, side: str) -> dict | None: ...
    def fills(self) -> list[FillDTO]: ...
    def orders(self) -> list[OrderDTO]: ...
    def prices(self) -> list[PriceDTO]: ...
    def quotes(self) -> list[QuoteDTO]: ...
    def vwaps(self) -> list[VwapDTO]: ...
    def today_ranges(self) -> list[TodayRangeDTO]: ...
    def fundamentals(self) -> list[FundamentalsDTO]: ...
    def account(self) -> AccountDTO | None: ...
    def health(self) -> dict: ...
    def session(self) -> dict: ...  # strategy plane (#212)
    async def request_stream(self, instrument_id: str) -> None: ...
    async def send_command(self, ctype: str, payload: dict) -> str: ...
    def command_status(self, command_id: str) -> dict | None: ...
    def bars(self) -> list[BarDTO]: ...
    async def bars_for(self, symbol: str, granularity: str) -> list[BarDTO]: ...


def create_node() -> Node:
    """Build the node selected by KUMO_ENGINE, else config/feed.toml's [engine].kind."""
    kind = os.environ.get("KUMO_ENGINE")
    if not kind:
        from api.feed_config import load_feed_config

        kind = load_feed_config().engine_kind
    kind = kind.strip().lower()

    if kind == "synthetic":
        from api.node import NodeManager

        return NodeManager()
    if kind == "live":
        from api.consumer import RedisConsumer

        return RedisConsumer()
    raise ValueError(f"unknown engine kind {kind!r} — expected 'live' or 'synthetic'")
