/**
 * Re-exports of the generated OpenAPI schema types under friendly names.
 * Source of truth: schema.ts (regenerated by `npm run gen:api`). Never hand-edit shapes here.
 */
import type { components } from "./schema";

export type PositionDTO = components["schemas"]["PositionDTO"];
export type PositionsResponse = components["schemas"]["PositionsResponse"];
export type TradeDTO = components["schemas"]["TradeDTO"];
export type TradesResponse = components["schemas"]["TradesResponse"];
export type WorkingOrderDTO = components["schemas"]["WorkingOrderDTO"];
export type InstrumentMatch = components["schemas"]["InstrumentMatch"];
export type InstrumentSearchResponse = components["schemas"]["InstrumentSearchResponse"];
export type HealthResponse = components["schemas"]["HealthResponse"];
export type BarDTO = components["schemas"]["BarDTO"];
export type FillDTO = components["schemas"]["FillDTO"];
export type OrderDTO = components["schemas"]["OrderDTO"];
export type AccountDTO = components["schemas"]["AccountDTO"];
export type OrdersResponse = components["schemas"]["OrdersResponse"];
export type BarMessage = components["schemas"]["BarMessage"];
export type FillMessage = components["schemas"]["FillMessage"];
export type StatusMessage = components["schemas"]["StatusMessage"];
export type SnapshotMessage = components["schemas"]["SnapshotMessage"];

/** Discriminated union of every frame the WS `/ws/stream` topic emits. */
export type WSMessage = BarMessage | FillMessage | StatusMessage | SnapshotMessage;
export type WatchlistResponse = components["schemas"]["WatchlistResponse"];
